module "appconfig_iam_profile" {
  source             = "../modules/AppConfigProfile/"
  profile_name       = "connect-config"
  application_id = var.application_id
  deployment_strategy_id = var.deployment_strategy_id
  content = {
    AWS_REGION = var.AWS_REGION,
    AWS_SECRET_NAME = var.AWS_SECRET_NAME,
    CONNECT_RMQ_APPLICATION_ID = var.CONNECT_RMQ_APPLICATION_ID,
    WORKFLOW_DOMAIN=var.WORKFLOW_DOMAIN,
    RABBITMQ_SECRET_NAME = var.RABBITMQ_SECRET_NAME,
    CONNECT_RMQ_EXCHANGE_NAME = var.CONNECT_RMQ_EXCHANGE_NAME,
    CONNECT_RMQ_EMAIL_QUEUE_NAME = var.CONNECT_RMQ_EMAIL_QUEUE_NAME,
    CONNECT_RMQ_EMAIL_ROUTING_KEY = var.CONNECT_RMQ_EMAIL_ROUTING_KEY,
    SES_TEST_EMAIL = var.SES_TEST_EMAIL,
    SES_CONFIGURATION_SET = var.SES_CONFIGURATION_SET,
    SES_FROM_EMAIL = var.SES_FROM_EMAIL,
    CONNECT_RMQ_EMAIL_STATUS_QUEUE_NAME = var.CONNECT_RMQ_EMAIL_STATUS_QUEUE_NAME,
    CONNECT_RMQ_SCHEDULER_QUEUE_NAME = var.CONNECT_RMQ_SCHEDULER_QUEUE_NAME,
    CONNECT_RMQ_SCHEDULER_ROUTING_KEY = var.CONNECT_RMQ_SCHEDULER_ROUTING_KEY,
    CONNECT_RMQ_EMAIL_STATUS_ROUTING_KEY = var.CONNECT_RMQ_EMAIL_STATUS_ROUTING_KEY,
    LOG_TO_DB = var.LOG_TO_DB,
    LOGIN_URL = var.LOGIN_URL
  }
}
